# Generated by Django 5.2.17 on 2026-09-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0002_cita_historialmedico_pacienteservicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
