# Generated by Django 5.2.17 on 2026-09-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion_clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion_clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Completado', max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.paciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='pacientes_atendidos',
            field=models.ManyToManyField(related_name='servicios_recibidos', through='gestion_clinica.PacienteServicio', to='gestion_clinica.paciente'),
        ),
    ]
